[tool.basedpyright]
reportImplicitRelativeImport = false
reportImplicitOverride = false
reportUnusedCallResult = false
reportUnannotatedClassAttribute = false
reportMissingTypeStubs = false
reportWildcardImportFromLibrary = false
reportAny = false
